rm(list=ls())

library(tidyverse)
library(ggdist)
library(ggh4x)
library(reshape2)
library(SpatialSablefishAssessment)
library(tictoc)
library(doParallel)

# library(afscOM) # may work but not certain

# Change to wherever your local copy of afscOM is
library(devtools)
afscOM_dir <- "~/Desktop/Projects/afscOM"
sablefishMSE_dir <- here::here()

devtools::load_all(afscOM_dir)
devtools::load_all(sablefishMSE_dir)

source("R/reference_points.R")
source("R/harvest_control_rules.R")
source("R/simulate_TAC.R")
source("R/age_structure_stats.R")
source("R/data_utils.R")
source("R/data_processing.R")
source("R/run_mse.R")
source("R/run_mse_multiple.R")
source("R/run_mse_parallel.R")
source("R/format_em_data.R")
source("R/fit_TMB_model.R")
source("R/recruitment_utils.R")
source("R/setup_mse_options.R")

#' 1. Set up the OM by defining demographic parameters
#' model options (such as options governing the observation
#' processes), and OM initial conditons
nyears <- 100

sable_om <- readRDS("data/sablefish_om_big.RDS") # Read this saved OM from a file

# Define recruitment to occur via historical resampling
assessment <- dget("data/sablefish_assessment_2023.rdat")
hist_recruits <- assessment$natage.female[,1]*2

om1 <- sable_om
om1$recruitment$func <- resample_recruits
om1$recruitment$pars <- list(
    hist_recruits = hist_recruits,
    nyears = nyears - length(hist_recruits) + 1
)

om2 <- sable_om
om2$recruitment$func <- resample_regime_recruits
om2$recruitment$pars <- list(
    regime1_recruits = hist_recruits[-c(20:24, 40:44, 57:63)],
    regime2_recruits = hist_recruits[c(20:24, 40:44, 57:63)],
    nyears = nyears - length(hist_recruits) + 1,
    regime_length = c(20, 5),
    starting_regime = 0
)

om3 <- sable_om
om3$recruitment$func <- beverton_holt
om3$recruitment$pars <- list(
    h = 0.7,
    R0 = 20,
    S0 = 282,
    sigR = 1.04
)

om_list <- listN(om1, om2, om3)

# sable_om$recruitment$func <- beverton_holt
# sable_om$recruitment$pars <- list(
#     h = 0.7,
#     R0 = 20,
#     S0 = 282,
#     sigR = 1.04
# )

# sable_om$recruitment$func <- resample_regime_recruits
# sable_om$recruitment$pars <- list(
#     regime1_recruits = hist_recruits[-c(20:24, 40:44, 57:63)],
#     regime2_recruits = hist_recruits[c(20:24, 40:44, 57:63)],
#     nyears = nyears - length(hist_recruits) + 1,
#     regime_length = c(20, 5),
#     starting_regime = 0
# )

# sable_om$recruitment$func <- resample_recruits
# sable_om$recruitment$pars <- list(
#     hist_recruits = hist_recruits,
#     nyears = nyears - length(hist_recruits) + 1
# )

# sable_om$recruitment$func <- regime_recruits
# sable_om$recruitment$pars <- list(
#     mus = c(25, 10),
#     cvs = c(0.40, 0.40),
#     nyears = nyears - length(hist_recruits) + 1,
#     regime_length = c(20, 20),
#     starting_regime = 0
# )

#' 2. Define a harvest control rule (HCR) function to use to project TAC
#' in future years. Such function must take accept the following parameters:
#' ref_pts: a list of reference points as generated by `calculate_ref_points`,
#'          (Fref and Bref)
#' naa: a vector of numbers-at-age for a given year (should be [1, nages, nsexes, nregions])
#' dem_params: a list of demographic parameter values subsetted to a single year
#' 
#' HCR functions can accept as many additional parameters as required.
#' 
#' Below is an example implementation of the NPFMCs Tier 3a HCR     
tier3 <- function(ref_pts, naa, dem_params){
    ssb <- apply(naa[,,1,]*dem_params$waa[,,1,,drop=FALSE]*dem_params$mat[,,1,,drop=FALSE], 1, sum)
    return(
        npfmc_tier3_F(ssb, ref_pts$Bref, ref_pts$Fref)
    )
}

# Going to start an MSE Options list distinct from everything else
mse_options <- setup_mse_options() # get default values
mse_options$management_procedure$management$tac_land_reduction <- 0.80 # only ~80% of TAC is used annually

mp1 <- mse_options
mp1$hcr <- list(
    func = tier3,
    extra_pars = NA,
    extra_options = list(
        max_stability = NA,
        harvest_cap = NA
    )
)

mp2 <- mse_options
mp2$hcr  <- list(
    func = tier3,
    extra_pars = NA,
    extra_options = list(
        max_stability = NA,
        harvest_cap = 25
    )
)

mp_list <- listN(mp1, mp2)

#' 3. Run the closed-loop MSE simulation
#' A single MSE simulation can be run using the `run_mse(...)`
#' function, while multiple MSE simulations can be run (serially)
#' using the `run_mse_multiple(...)` function.
#' 
#' It is recommended to always use `run_mse_multiple(...)` even
#' when only a single MSE simulation is required.
set.seed(1007)
nsims <- 1
seed_list <- sample(1:(1000*nsims), nsims)  # Draw 10 random seeds

model_runs2 <- run_mse_multiple(om_list, mp_list, seed_list, nyears=100, mse_options=mse_options)

extra_columns2 <- list(
    om=names(om_list),
    hcr=names(mp_list)
)

# model_runs <- mse_objects

ssb_data <- get_ssb_biomass(model_runs2, extra_columns2, sable_om$dem_params)
plot_ssb(ssb_data, v1="hcr", v2="om")

# Plot fishing mortality rates from OM and EM
f_data <- get_fishing_mortalities(model_runs2, extra_columns2)
plot_fishing_mortalities(f_data, v1="hcr", v2="om")

r_data <- get_recruits(model_runs2, extra_columns2)
plot_recruitment(r_data, v1="hcr", v2="om")

abctac <- get_management_quantities(model_runs2, extra_columns2)
plot_abc_tac(abctac, v1="hcr", v2="om")

catch_data <- get_landed_catch(model_runs2, extra_columns2)
plot_landed_catch(catch_data, v1="hcr", v2="om")
