rm(list=ls())

library(tidyverse)
library(ggdist)
library(ggh4x)
library(reshape2)
library(SpatialSablefishAssessment)
library(tictoc)
library(doParallel)
# library(afscOM)
# library(afscOM) # may work but not certain

# Change to wherever your local copy of afscOM is
library(devtools)
afscOM_dir <- "~/Desktop/Projects/afscOM"
sablefishMSE_dir <- here::here()

devtools::load_all(afscOM_dir)
# devtools::load_all(sablefishMSE_dir)

lapply(list.files("R", full.names = TRUE), source)

#' 1. Set up the OM by defining demographic parameters
#' model options (such as options governing the observation
#' processes), and OM initial conditons
nyears <- 110

sable_om <- readRDS("data/sablefish_om_big.RDS") # Read this saved OM from a file
sable_om$model_options$fleet_apportionment <- matrix(c(0.80, 0.20), nrow=nrow(sable_om$model_options$fleet_apportionment), ncol=2, byrow=TRUE)

source("dev/oms.R")
om_list <- listN(
    om_rand_recruit,
    om_cylic_recruit,
    om_bh_recruit,
    om_low_recruit,
    om_high_recruit, 
    om_crash_recruit,
    om_bhcyclic_recruit
)


#' 2. Define a harvest control rule (HCR) function to use to project TAC
#' in future years. Such function must take accept the following parameters:
#' ref_pts: a list of reference points as generated by `calculate_ref_points`,
#'          (Fref and Bref)
#' naa: a vector of numbers-at-age for a given year (should be [1, nages, nsexes, nregions])
#' dem_params: a list of demographic parameter values subsetted to a single year
#' 
#' HCR functions can accept as many additional parameters as required.
#' 
#' Below is an example implementation of the NPFMCs Tier 3a HCR     
source("dev/hcrs.R")

hcr_list <- listN(
    mp_f40, 
    mp_b30f40, 
    mp_b30f50, 
    mp_b40f50, 
    mp_b40f55, 
    mp_f50, 
    mp_f40cons,
    mp_10cap,
    mp_15cap,
    mp_20cap,
    mp_20cap_cons,
    mp_25cap,
    mp_25cap_cons,
    mp_10perc,
    mp_15perc,
    mp_25perc,
    mp_f50chr,
    mp_f55chr,
    mp_f00chr,
    mp_agedevs,
    mp_ageblocks,
    mp_ageswitch,
    mp_pfmc4010
)

#' 3. Run the closed-loop MSE simulation
#' A single MSE simulation can be run using the `run_mse(...)`
#' function, while multiple MSE simulations can be run (serially)
#' using the `run_mse_multiple(...)` function.
#' 
#' It is recommended to always use `run_mse_multiple(...)` even
#' when only a single MSE simulation is required.
# om_list = listN(om1, om2)
# hcr_list = listN(mp1, mp2, mp3, mp5, mp8, mp9, mp10, mp12, mp13, mp15)
# hcr_list <- listN(mp1)

# 857, 1120, 1007, 895
set.seed(895)
nsims <- 9
seed_list <- sample(1:(1000*nsims), nsims)  # Draw 10 random seeds
seed_list <- c(3,40,311,417,1105,1259,1581,1819,2078,2330,2512,2563,2719,2861,3190,3452,3709,3899,4233,4716,4723,4852,5160,5938,6264,6533,6754,7149,7207,7284,7329,7557,7579,8003,8388,8904)#ssb_data2 %>% pull(sim) %>% unique


mse_options_base <- setup_mse_options()
mse_options <- mse_options_base
mse_options$n_spinup_years <- 54
mse_options$recruitment_start_year <- 54
mse_options$n_proj_years <- 75

mse_options_list <- listN(mse_options)#, mse_options2, mse_options3)


om_list <- listN(om_rand_recruit, om_crash_recruit, om_bhcyclic_recruit)
hcr_list <- listN(mp_f40, mp_f40chr, mp_f50chr, mp_f55chr)

# mp5_modelrun <- run_mse_parallel(nsims, seed_list, om1, mp5, mse_options, nyears)
tic()
model_runs <- run_mse_multiple(
    om_list, 
    hcr_list, 
    seed_list,
    nyears=100,
    mse_options_list=mse_options_list,
    diagnostics = TRUE
)

toc()

filter_hcrs <- function(data, hcr_type){
    return(
        data %>% mutate(
            hcr_class = case_when(
                grepl("Harvest Cap", hcr) ~ "Harvest Cap",
                grepl("Age", hcr) ~ "Age Structured",
                grepl("+/-", hcr) ~ "Stability Constraints",
                TRUE ~ "Reference Points"
            )
        ) %>%
        filter(hcr_class == hcr_type | hcr == "F40")
    )
}

hcr_groups <- c("Harvest Caps", "Age Structured", "Stability Constraints", "Constant F", "Reference Points")

om_names <- unlist(lapply(om_list, \(x) x$name))
hcr_names <- unlist(lapply(hcr_list, \(x) x$name))

extra_columns2 <- expand.grid(
    om = unlist(lapply(om_list, \(x) x$name)),
    hcr = unlist(lapply(hcr_list, \(x) x$name))
) %>% as_tibble() %>%
as.data.frame

mse_runs <- get_saved_model_runs(om_order=om_names, hcr_order=hcr_names)
model_runs <- mse_runs$model_runs
extra_columns2 <- mse_runs$extra_columns2

interval_widths <- c(0.50, 0.80)
common_trajectory <- 54

publication_hcrs <- c("F40", "F50", "B40/F50", "F40 +/- 5%", "F40 +/- 10%", "15k Harvest Cap", "25k Harvest Cap", "Constant F50", "PFMC 40-10", "British Columbia", "No Fishing")
hcr_colors <- set_hcr_colors(publication_hcrs)

# model_runs <- mse_runs$model_runs
plot_mse_summary(model_runs, extra_columns2, dem_params=sable_om$dem_params, hcr_filter=hcr_names, om_filter=om_names, common_trajectory = common_trajectory)+custom_theme
ggsave(filename=file.path("~/Desktop/", "summary2.png"), width=10, height=7, units="in")

# Plot spawning biomass
ssb_data <- get_ssb_biomass(model_runs, extra_columns2, sable_om$dem_params, hcr_filter=publication_hcrs, om_filter=om_names)
plot_ssb(ssb_data, v1="hcr", v2="om", v3=NA, common_trajectory=common_trajectory, show_est = FALSE)+custom_theme+guides(color=guide_legend(title="HCR", ncol=4))
plot_relative_ssb(ssb_data, v1="hcr", v2="om", common_trajectory = common_trajectory, base_hcr = "No Fishing")+custom_theme+guides(color=guide_legend(title="HCR", ncol=4))
plot_ssb_paginate(ssb_data, v1="hcr", v2="om", v3=NA, common_trajectory=common_trajectory, show_est = FALSE)


ggsave(filename=file.path(here::here(), "figures", "rel_ssb.png"), width=8, height=8, units=c("in"))


# Plot fishing mortality rates from OM and EM
f_data <- get_fishing_mortalities(model_runs, extra_columns2, hcr_filter=hcr_names, om_filter=om_names)
plot_fishing_mortalities(f_data, v1="hcr", v2="om", common_trajectory = common_trajectory, show_est=FALSE)+custom_theme
ggsave(filename=file.path("~/Desktop/sablefish_plots", "fishing_mortality.png"), width=8, height=8, units=c("in"))

# Plot management quantities (ABC, TAC, Expected Landings, and Attainment)
abctac <- get_management_quantities(model_runs, extra_columns2, spinup_years=common_trajectory, hcr_filter=hcr_names, om_filter=om_names)
plot_abc_tac(abctac, v1="hcr", v2="om", common_trajectory=common_trajectory)+custom_theme
ggsave(filename=file.path("~/Desktop/sablefish_plots", "abc_tac.png"), width=10*1.7, height=6*1.7, units=c("in"))

abctac %>% filter(time > 64) %>%
    group_by(om, hcr, L1) %>%
    median_qi(value, .width=c(0.50)) %>%
    select(om, hcr, L1, value) %>%
    filter(L1 %in% c("ABC")) %>%
    pivot_wider(names_from=hcr, values_from=value)

# Plot landed catch
catch_data <- get_landed_catch(model_runs, extra_columns2, hcr_filter=publication_hcrs, om_filter=om_names)
plot_landed_catch(catch_data, v1="hcr", v2="om", common_trajectory = common_trajectory)+custom_theme
plot_catch_paginate(catch_data, v1="hcr", v2="om", common_trajectory = common_trajectory, base_hcr="F40")
ggsave(filename=file.path(here::here(), "figures", "catch.png"), width=8, height=8, units=c("in"))

for(g in hcr_groups){
    plot_ssb_catch(
        model_runs, extra_columns2, sable_om$dem_params, 
        v1="hcr", v2="om", v3=NA, common_trajectory = common_trajectory,
        hcr_filter = publication_hcrs, om_filter=om_names
    )+custom_theme
    ggsave(filename=file.path("~/Desktop/sablefish_plots", paste0("ssb_catch_", g ,".png")), width=13, height=10, units=c("in"))
}

# Plot phase-plane diagrams (F vs SSB, HCR v SSB, Catch v SSB)
ref_pts <- get_reference_points(model_runs, extra_columns2, hcr_filter=hcr_names, om_filter=om_names, seed_list)

phaseplane_data <- get_phaseplane_data(model_runs, extra_columns2, sable_om$dem_params)
phaseplane_data2 <- phaseplane_data
plot_phase_diagram(phaseplane_data2, ref_pts, common_trajectory = common_trajectory)+custom_theme

hcrphase_data <- get_hcrphase_data(model_runs, extra_columns2, sable_om$dem_params, hcr_filter=hcr_names, om_filter=om_names)
hcrphase_data2 <- hcrphase_data
plot_hcr_phase_diagram(hcrphase_data, ref_pts, common_trajectory = common_trajectory)+custom_theme

catchphase_data <- get_phaseplane_catch_data(model_runs, extra_columns2, sable_om$dem_params)
plot_catch_phase_diagram(catchphase_data, ref_pts, common_trajectory = common_trajectory)+custom_theme

b40s <- get_b40_timeseries(model_runs, extra_columns2, hcr_names, om_names)
ggplot(b40s)+
    geom_lineribbon(aes(x=time, y=B40, ymin=.lower, ymax=.upper))+
    scale_fill_brewer(palette="Blues")+
    scale_y_continuous(limits=c(0, 200))+
    facet_wrap(~om)+
    custom_theme

# Plot recruitment
rec_data <- get_recruits(model_runs, extra_columns2, hcr_filter=hcr_names, om_filter=om_names)
plot_recruitment(rec_data, v1="hcr", v2="om", show_est = FALSE)+custom_theme

###### Performance Metrics
time_horizon <- c(55, 130)

performance_metrics <- performance_metric_summary(
    model_runs, 
    extra_columns2, 
    sable_om$dem_params, 
    ref_naa,
    interval_widths=c(0.50, 0.80),
    time_horizon = time_horizon, 
    extra_filter = NULL,
    relative=NULL, 
    summarise_by=c("om", "hcr"),
    hcr_filter=hcr_names,
    om_filter=om_names
)

# perf_data <- performance_metrics$perf_data %>% filter(hcr %in% publication_hcrs)
publication_metrics = c("Annual Catch", "Catch AAV", "Large Catch", "SSB", "Average Age", "Proprtion Years Low SSB")
perf_data2 <- performance_metrics$perf_data %>% 
    filter(hcr %in% publication_hcrs, name %in% publication_metrics) %>%
    mutate(
            hcr = factor(hcr, levels=publication_hcrs),
            om = factor(om, labels=c("Random Recruitment", "BH Recruitment", "BH Regime Recruitment", "Crash Recruitment")),
            name = factor(name, levels=publication_metrics)
    )

plot_performance_metric_summary(perf_data2, v2="om", is_relative=FALSE)+
    custom_theme+guides(color="none", shape="none")+
    theme(panel.spacing.x = unit(1.25, "cm"))+ 
    ggh4x::facetted_pos_scales(
        x = list(
            scale_x_continuous(limits=c(0, 55)),
            scale_x_continuous(limits=c(0, 0.06), breaks=c(0, 0.02, 0.04, 0.06)),
            scale_x_continuous(limits=c(0, 1), breaks=c(0, 0.50, 1.0)),
            scale_x_continuous(limits=c(0, 550), breaks=c(0, 150, 300, 450)),
            scale_x_continuous(limits=c(0, 15)),
            scale_x_continuous(limits=c(0, 0.60), breaks=c(0.0, 0.20, 0.40, 0.60))
        )
    )
ggsave(filename=file.path(here::here(), "figures", "performance2.png"), width=18, height=12, units=c("in"))


##### Resiliency Metrics
crash_time <- biomass_crash_time(
    model_runs, 
    extra_columns2, 
    sable_om$dem_params, 
    interval_widths=c(0.50, 0.80),
    time_horizon = time_horizon, 
    extra_filter = NULL,
    relative=NULL, 
    summarise_by=c("om", "hcr"),
    hcr_filter=hcr_names,
    om_filter=c("Immediate Crash Recruitment")
)

recovery_time <- biomass_recovery_time(
    model_runs, 
    extra_columns2, 
    sable_om$dem_params, 
    interval_widths=c(0.50, 0.80),
    time_horizon = time_horizon, 
    extra_filter = NULL,
    relative=NULL, 
    summarise_by=c("om", "hcr"),
    hcr_filter=hcr_names,
    om_filter=c("Immediate Crash Recruitment")
)


crash_recovery_time <- crash_time %>% reformat_ggdist_long(n=2) %>%
     bind_rows(recovery_time %>% reformat_ggdist_long(n=2)) %>%
     filter(hcr %in% publication_hcrs) %>%
     mutate(
            name=factor(name, labels=c("Crash Time", "Recovery Time")),
            hcr = factor(hcr, levels=publication_hcrs)
    )

ggplot(crash_recovery_time)+
    geom_pointinterval(aes(x=median, xmin=lower, xmax=upper, y=hcr, color=hcr), point_size=3, position="dodge")+
    facet_wrap(~name, scales="free_x")+
    # geom_vline(data=summary, aes(xintercept = median), color="black")+
    scale_shape_discrete()+
    scale_color_manual(values=hcr_colors)+
    scale_x_continuous("Years", limits=c(0, 20))+
    # facet_wrap(vars(name), scales="free_x")+
    labs(y="", x="", shape="OM", color="HCR")+
    coord_cartesian(expand=0)+
    guides(shape=guide_legend(nrow=3), color="none")+
    custom_theme+
    theme(
        plot.title = element_text(size=16),
        plot.margin = margin(0.24, 1, 0.25, 0.25, unit="cm"),
        panel.spacing.x = unit(1, "cm"),
    )
ggsave(file.path(here::here(), "figures", "resilience_metrics.jpeg"), width=12, height=8, units="in")


#### F vs SSB Relationship
f_ssb_data <- ssb_data %>% filter(L1 == "naa") %>% 
    left_join(f_data %>% filter(L1 == "faa", fleet=="Fixed") %>% select(-c(F)), by=c("time", "sim", 'om', "hcr")) %>% 
    filter(time >= 54) %>%
    group_by(om, hcr) %>%
    median_qi(total_F, spbio, .width=interval_widths, na.rm=TRUE)

model_preds <- ssb_data %>% filter(L1 == "naa") %>% 
    left_join(f_data %>% filter(L1 == "faa", fleet=="Fixed") %>% select(-c(F)), by=c("time", "sim", 'om', "hcr")) %>% 
    filter(time >= 54, !is.na(total_F)) %>%
    group_by(om, hcr, sim) %>%
    summarise(
        spbio=median(spbio),
        total_F=median(total_F, na.rm=TRUE)
    ) %>%
    nest(data = -c("om")) %>%
    mutate(
        model = map(data, ~lm(spbio ~ total_F, data=.))
    ) %>%
    mutate(
        glanced = map(model, glance),
        preds = map(model, ~predict(., newdata=data.frame(total_F=seq(0, 0.15, 0.001))))
    ) %>%
    unnest(c(glanced, preds)) %>%
    select(c(om, r.squared, preds)) %>%
    ungroup() %>%
    mutate(
        total_F=rep(seq(0, 0.15, 0.001), 4)
    )

ggplot(model_preds)+
    geom_pointrange(data=f_ssb_data, aes(x=total_F, xmin=total_F.lower, xmax=total_F.upper, y=spbio, ymin=spbio.lower, ymax=spbio.upper, color=hcr, label=hcr), size=1)+
    geom_line(aes(x=total_F, y=preds), linetype="dashed")+
    geom_label(aes(x=0.016, y=25, label=paste0("R^2=",round(r.squared, 3))), size=6)+
    scale_x_continuous("FIshing Mortality Rate", limits = c(-0.005, 0.1), breaks=seq(0, 0.1, 0.025), labels=c("0", "0.025", "0.050", "0.075", "0.1"))+
    scale_y_continuous("Spawning Biomass (1000s mt)", limits = c(0,350))+
    coord_cartesian(expand=0)+
    labs(color="HCR")+
    facet_wrap(~om)+
    custom_theme+
    theme(
        panel.spacing.x = unit(1, "cm"),
        plot.margin = margin(0.5, 1, 0.5, 0.5, "cm")
    )
ggsave(filename=file.path(here::here(), "figures", "ssb_v_f.jpeg"))



#### Example recruitment functions
examp_rec <- get_recruits(model_runs, extra_columns2, hcr_filter=c("F40"), om_filter=om_names) %>%
    as_tibble() %>%
    filter(time > 54, sim %in% sample(seed_list, 5), hcr == "F40") %>%
    mutate(
        sim = factor(sim)
    )

mean_rec <- examp_rec %>%
    group_by(om) %>%
    summarise(r=median(rec))

summ_rec <- get_recruits(model_runs, extra_columns2, hcr_filter=c("F40"), om_filter=om_names) %>%
    as_tibble() %>%
    filter(time > 54, hcr == "F40") %>%
    group_by(time, om) %>%
    median_qi(rec, .width=interval_widths)

ggplot(examp_rec) +
    geom_line(aes(x=time, y=rec, color=om, group=sim), size=0.5, alpha=0.6)+
    geom_line(data=summ_rec, aes(x=time, y=rec), color="black", size=1)+
    geom_hline(data=mean_rec, aes(yintercept=r), linetype="dashed")+
    geom_text(data=mean_rec, aes(x=123, y=110, label=round(r, 2)), size=6)+
    scale_y_continuous(limits=c(0, 120))+
    scale_x_continuous(breaks=c(seq(55, 130, 20), 134), labels=c(seq(0, 75, 20), 75))+
    guides(color="none")+
    labs(x="Time", y="Recruitment")+
    coord_cartesian(expand=0)+
    facet_wrap(~om, ncol=2)+
    theme_bw()+
    custom_theme
ggsave(filename=file.path(here::here(), "figures", "example_recruitment.png"), width=13, height=10, units = "in")


#### Pairs Plot for Catch, SSB, Large Catch, Population Age
extra_columns=extra_columns2 
dem_params=sable_om$dem_params
relative=NULL
summarise_by=c("om", "hcr")
group_columns <- c("sim", summarise_by)

avg_F <- f_data %>% ungroup() %>% filter(L1 == "faa") %>%
    filter_times(time_horizon) %>%
    relativize_performance(
        rel_column = "hcr",
        value_column = "annual_catch",
        rel_value = relative,
        grouping=group_columns
    ) %>%
    select(time, sim, om, hcr, total_F)

avg_catch <- bind_mse_outputs(model_runs, "caa", extra_columns) %>%
    as_tibble() %>%
    filter_times(time_horizon) %>%
    group_by(across(all_of(c("time", group_columns)))) %>%
    summarise(annual_catch = sum(value)) %>%
    relativize_performance(
        rel_column = "hcr",
        value_column = "annual_catch",
        rel_value = relative,
        grouping=group_columns
    )
    
avg_ssb <- get_ssb_biomass(model_runs, extra_columns, dem_params, hcr_filter = hcr_names, om_filter=om_names) %>%
    ungroup() %>%
    filter(L1 != "naa_est") %>%
    select(-L1) %>%
    filter_times(time_horizon=time_horizon) %>%
    relativize_performance(
        rel_column = "hcr",
        value_column = "spbio",
        rel_value = relative,
        grouping = group_columns
    )

avg_age <- bind_mse_outputs(model_runs, "naa", extra_columns) %>%
    as_tibble() %>%
    ungroup() %>%
    group_by(time, age, sim, om, hcr) %>%
    mutate(value = sum(value)) %>%
    filter(sex == "F") %>%
    ungroup() %>%
    group_by(time, sim, hcr, om) %>%
    summarise(
        avg_age = compute_average_age(value, 2:31)
    ) %>%
    filter_times(time_horizon=time_horizon) %>%
    relativize_performance(
        rel_column = "hcr",
        value_column = "avg_age",
        rel_value = relative,
        grouping = group_columns
    )

prop_lg_catch <- bind_mse_outputs(model_runs, "caa", extra_columns) %>%
    as_tibble() %>%
    filter_times(time_horizon = time_horizon) %>%
    mutate(
        size_group = case_when(
            age < 5 ~ "Small",
            age < 9 ~ "Medium",
            TRUE ~ "Large"
        )
    ) %>%
    group_by(across(all_of(c("time", "size_group", group_columns)))) %>%
    summarise(total_catch = sum(value)) %>%
    ungroup() %>%
    pivot_wider(names_from = "size_group", values_from="total_catch") %>%
    rowwise() %>%
    mutate(
        total_catch = sum(Large, Medium, Small)
    ) %>%
    mutate(across(Large:Small, ~ ./total_catch)) %>%
    select(-total_catch) %>%
    ungroup() %>%
    pivot_longer(Large:Small, names_to="size_group", values_to="catch") %>%
    relativize_performance(
        rel_column = "hcr",
        value_column = "catch",
        rel_value = relative,
        grouping = c("size_group", group_columns)
    )

my_fn2 <- function(data, mapping, ...){
    print(data)
    p <- ggplot(data = data, mapping = mapping) + 
        geom_point(aes(color=hcr), size=2) + 
        geom_smooth(method=lm, aes(color=hcr), se=FALSE, ...) +
        ggpmisc::stat_poly_line(data=data, mapping=aes(), color="black", linetype="dashed")+
        ggpmisc::stat_poly_eq(data=data, mapping=aes(x=data$x, y=data$y), use_label("eq"))
        # geom_smooth(method=lm, color="black", linetype="dashed", ...)
    p
}

gpairs_lower <- function(g){
    g$plots <- g$plots[-(1:g$nrow)]
    g$yAxisLabels <- g$yAxisLabels[-1]
    g$nrow <- g$nrow -1

    g$plots <- g$plots[-(seq(g$ncol, length(g$plots), by = g$ncol))]
    g$xAxisLabels <- g$xAxisLabels[-g$ncol]
    g$ncol <- g$ncol - 1

    g
}

gp <- avg_F %>%
    left_join(avg_catch, by=c("time", "sim", "om", "hcr")) %>% 
    left_join(avg_ssb, by=c("time", "sim", "om", "hcr")) %>%
    left_join(avg_age, by=c("time", "sim", "om", "hcr")) %>%
    left_join(prop_lg_catch %>% filter(size_group == "Large") %>% select(time, sim, om, hcr, catch), by=c("time", "sim", "om", "hcr")) %>%
    filter(hcr %in% publication_hcrs, !(hcr %in% c("No Fishing"))) %>%
    group_by(sim, hcr) %>%
    median_qi(total_F, annual_catch, spbio, catch, avg_age, .width=c(0.50)) %>%
    select(hcr, total_F, annual_catch, spbio, catch, avg_age) %>%
    rename("Annual Catch"="annual_catch", "SSB"="spbio", "Large Catch"="catch", "Population Age"="avg_age") %>%

    ggpairs(
        columns=c(3:6),
        aes(color=hcr),
        lower=list(continuous=my_fn2),
        # upper=list(continuous = wrap(ggally_cor, method = "pearson")),
        legend=c(1, 1)
    )+
    custom_theme

g1 <- gp[1, 1]
g1 <- g1 + coord_cartesian(ylim=c(0, 1))
gp[1, 1] <- g1

ggsave(gp, filename=file.path(here::here(), "figures", "performance_pairs2.jpeg"), width=10, height=10, units="in")