rm(list=ls())

library(ggdist)
library(ggh4x)
library(reshape2)
library(SpatialSablefishAssessment)
library(tictoc)
library(doParallel)

# library(afscOM) # may work but not certain

# Change to wherever your local copy of afscOM is
library(devtools)
afscOM_dir <- "~/Desktop/Projects/afscOM" 
devtools::load_all(afscOM_dir)

source("R/reference_points.R")
source("R/harvest_control_rules.R")
source("R/simulate_TAC.R")
source("R/age_structure_stats.R")
source("R/data_utils.R")
source("R/data_processing.R")
source("R/run_mse.R")
source("R/run_mse_multiple.R")
source("R/run_mse_parallel.R")
source("R/format_em_data.R")
source("R/fit_TMB_model.R")

#' 1. Set up the OM by defining demographic parameters
#' model options (such as options governing the observation
#' processes), and OM initial conditons
sable_om <- readRDS("data/sablefish_om.RDS") # Read this saved OM from a file
sable_om$model_options$simulate_observations <- TRUE # Enable simulating observations
# Generated 50 age composition samples from the LL survey and fixed gear fishery
sable_om$model_options$obs_pars$surv_ll$ac_samps <- 50
sable_om$model_options$obs_pars$surv_tw$ac_samps <- 50
sable_om$model_options$obs_pars$fish_fx$ac_samps <- 50
sable_om$model_options$obs_pars$fish_tw$ac_samps <- 50
# Generate age comp samples as integers rather than proportions
# (this is necesarry for the SpatialSablefishAssessment TMB model)
sable_om$model_options$obs_pars$surv_ll$as_integers = TRUE
sable_om$model_options$obs_pars$surv_tw$as_integers = TRUE
sable_om$model_options$obs_pars$fish_fx$as_integers = TRUE
sable_om$model_options$obs_pars$fish_tw$as_integers = TRUE
# Decrease observation error
sable_om$model_options$obs_pars$surv_ll$rpn_cv <- 0.10
sable_om$model_options$obs_pars$surv_ll$rpw_cv <- 0.10
sable_om$model_options$obs_pars$surv_tw$rpw_cv <- 0.10
# Turn on estimation model
sable_om$model_options$run_estimation = TRUE

#' 2. Define a harvest control rule (HCR) function to use to project TAC
#' in future years. Such function must take accept the following parameters:
#' ref_pts: a list of reference points as generated by `calculate_ref_points`,
#'          (B40, F35, and F40)
#' naa: a vector of numbers-at-age for a given year (should be [1, nages, nsexes, nregions])
#' dem_params: a list of demographic parameter values subsetted to a single year
#' 
#' HCR functions can accept as many additional parameters as required.
#' 
#' Below is an example implementation of the NPFMCs Tier 3a HCR     
tier3 <- function(ref_pts, naa, dem_params){
    ssb <- apply(naa[,,1,]*dem_params$waa[,,1,,drop=FALSE]*dem_params$mat[,,1,,drop=FALSE], 1, sum)
    return(
        npfmc_tier3_F(ssb, ref_pts$B40, ref_pts$F40)
    )
}

#' 3. Run the closed-loop MSE simulation
#' A single MSE simulation can be run using the `run_mse(...)`
#' function, while multiple MSE simulations can be run (serially)
#' using the `run_mse_multiple(...)` function.
#' 
#' It is recommended to always use `run_mse_multiple(...)` even
#' when only a single MSE simulation is required.
set.seed(1007)
nsims <- 10
seeds <- sample(1:(1000*nsims), nsims)  # Draw 10 random seeds

tic()
mse_tier3     <- run_mse_parallel(nsims=nsims, seeds=seeds, nyears=100, om=sable_om, hcr=tier3)
toc()

# nsims <- 1
# seeds <- sample(1:(1000*nsims), nsims)  # Draw 10 random seeds
# ms_small <- run_mse_multiple(nsims=nsims, seeds=seeds, nyears=100, om=sable_om, hcr=tier3)

# Example of running a single MSE simulation
# mse_tier3     <- run_mse(om=sable_om, hcr=tier3, nyears_input=100)

#' 4. Process MSE results
#' An example processing routine to plot the OM spawning biomass,
#' aggregated over multiple simulations, alongside the EM estimate
#' of spawning biomass.
model_runs <- list(
    mse_tier3
    # ms_small
)
extra_columns <- list(
    hcr = c("tier3")
)

# Plot spawning biomass from OM and EM
d <- get_ssb_biomass(model_runs, extra_columns, sable_om$dem_params) %>%
    # SSB is females only
    filter(sex == "F") %>%
    # summarise SSB across year and sim 
    group_by(time, hcr, sim, L1) %>%
    summarise(spbio=sum(spbio)) %>%
    # Compute quantiles of SSB distribution
    group_by(time, hcr, L1) %>%
    median_qi(spbio, .width=c(0.50, 0.80), .simple_names=FALSE) %>%
    # Reformat ggdist tibble into long format
    reformat_ggdist_long(n=3)


ggplot(d %>% filter(L1 == "naa")) + 
    geom_lineribbon(aes(x=time, y=median, ymin=lower, ymax=upper, group=hcr), size=0.4)+
    geom_pointrange(data = d %>% filter(L1 == "naa_est"), aes(x=time, y=median, ymin=lower, ymax=upper), alpha=0.35, color="red")+
    geom_vline(xintercept=64, linetype="dashed")+
    scale_fill_brewer(palette="Blues")+
    scale_y_continuous(limits=c(0, 300))+
    coord_cartesian(expand=0)+
    theme_bw()

# Plot fishing mortality rates from OM and EM
f <- get_fishing_mortalities(model_runs, extra_columns) %>%
    group_by(time, fleet, L1, hcr) %>%
    median_qi(F, total_F, .width=c(0.50, 0.80), .simple_names=TRUE) %>%
    reformat_ggdist_long(n=4) %>%
    filter(name == "total_F")

ggplot(f %>% filter(L1 == "faa")) + 
    geom_lineribbon(aes(x=time, y=median, ymin=lower, ymax=upper, group=hcr), size=0.4)+
    geom_pointrange(data = f %>% filter(L1 == "faa_est"), aes(x=time, y=median, ymin=lower, ymax=upper), alpha=0.35, color="red")+
    geom_vline(xintercept=64, linetype="dashed")+
    scale_fill_brewer(palette="Blues")+
    scale_y_continuous(limits=c(0, 0.30))+
    coord_cartesian(expand=0)+
    theme_bw()


# Plot ABC, TAC, and landings
bind_mse_outputs(model_runs, c("abc", "tac", "exp_land"), extra_columns = extra_columns) %>%
    as_tibble() %>%
    drop_na() %>%
    group_by(time, L1) %>%
    median_qi(value, .width=c(0.50, 0.80), .simple_names=FALSE) %>%
    reformat_ggdist_long(n=2) %>%

  ggplot()+
    geom_pointrange(aes(x=time, y=median, ymin=lower, ymax=upper, color=L1))+
    geom_line(aes(x=time, y=median, color=L1, group=L1))+
    scale_y_continuous(limits=c(0, 50))+
    theme_bw()


# Plot recruitment from OM and EM
get_recruits(model_runs, extra_columns) %>%
    # summarise SSB across year and sim 
    group_by(time, L1) %>%
    median_qi(rec, .width=c(0.50, 0.80), .simple_names=FALSE) %>%
    reformat_ggdist_long(n=2) %>%

    ggplot() + 
      geom_line(aes(x=time, y=median, group=L1, color=L1), size=0.4)+
      geom_vline(xintercept=64, linetype="dashed")+
      scale_fill_brewer(palette="Blues")+
      scale_y_continuous(limits=c(0, 100))+
      coord_cartesian(expand=0)+
      theme_bw()






nmodels <- length(mse_tier3$model_outs$reps)
o <- lapply(seq_along(1:nmodels), function(i){
  y <- (i-1)%/%nsims+1
  s <- (i-1)%%nsims+1
  o <- SpatialSablefishAssessment::get_SSB(mse_tier3$model_outs$reps[y, s][[1]]) %>% filter(Year == max(Year))
  o$sim <- seeds[s]
  return(o)
})

est_ssb <- bind_rows(o)

names(mse_tier3$model_outs$reps[1,1][[1]])


derive_est_naa <- function(model_outs, nyears, nsims){
    naa_out <- array(NA, dim=c(nyears, 30, 2, 1, nsims))
    nmodels <- length(mse_tier3$model_outs$reps)
    for(i in 1:nmodels){
        y <- (i-1)%/%nsims+1
        s <- (i-1)%%nsims+1
        est_naa_f <- model_outs$reps[y, s][[1]]$natage_f
        est_naa_m <- model_outs$reps[y, s][[1]]$natage_m
        naa_out[63+y,,1,1,s] <- est_naa_f[,ncol(est_naa_f)]
        naa_out[63+y,,2,1,s] <- est_naa_m[,ncol(est_naa_m)]
    }
    return(naa_out)
}

derive_est_naa(mse_tier3$model_outs, 160, nsims)
