rm(list=ls())

library(tidyverse)
library(ggdist)
library(ggh4x)
library(reshape2)
library(SpatialSablefishAssessment)
library(tictoc)
library(doParallel)
# library(afscOM)
# library(afscOM) # may work but not certain

# Change to wherever your local copy of afscOM is
library(devtools)
afscOM_dir <- "~/Desktop/Projects/afscOM"
sablefishMSE_dir <- here::here()

devtools::load_all(afscOM_dir)
# devtools::load_all(sablefishMSE_dir)

lapply(list.files("R", full.names = TRUE), source)

#' 1. Set up the OM by defining demographic parameters
#' model options (such as options governing the observation
#' processes), and OM initial conditons
nyears <- 110

sable_om <- readRDS("data/spatial_sablefish_om.RDS") # Read this saved OM from a file
# sable_om$model_options$fleet_apportionment <- matrix(c(0.80, 0.20), nrow=nrow(sable_om$model_options$fleet_apportionment), ncol=2, byrow=TRUE)

source("dev/oms.R")
om_list <- listN(
    om_rand_recruit,
    om_cylic_recruit,
    om_bh_recruit,
    om_low_recruit,
    om_high_recruit, 
    om_crash_recruit,
    om_bhcyclic_recruit
)


#' 2. Define a harvest control rule (HCR) function to use to project TAC
#' in future years. Such function must take accept the following parameters:
#' ref_pts: a list of reference points as generated by `calculate_ref_points`,
#'          (Fref and Bref)
#' naa: a vector of numbers-at-age for a given year (should be [1, nages, nsexes, nregions])
#' dem_params: a list of demographic parameter values subsetted to a single year
#' 
#' HCR functions can accept as many additional parameters as required.
#' 
#' Below is an example implementation of the NPFMCs Tier 3a HCR     
source("dev/hcrs.R")

hcr_list <- listN(
    mp_f40, 
    mp_b30f40, 
    mp_b30f50, 
    mp_b40f50, 
    mp_b40f55, 
    mp_f50, 
    mp_f40cons,
    mp_10cap,
    mp_15cap,
    mp_20cap,
    mp_20cap_cons,
    mp_25cap,
    mp_25cap_cons,
    mp_10perc,
    mp_15perc,
    mp_25perc,
    mp_f50chr,
    mp_f55chr,
    mp_f00chr,
    mp_agedevs,
    mp_ageblocks,
    mp_ageswitch,
    mp_pfmc4010
)

#' 3. Run the closed-loop MSE simulation
#' A single MSE simulation can be run using the `run_mse(...)`
#' function, while multiple MSE simulations can be run (serially)
#' using the `run_mse_multiple(...)` function.
#' 
#' It is recommended to always use `run_mse_multiple(...)` even
#' when only a single MSE simulation is required.
# om_list = listN(om1, om2)
# hcr_list = listN(mp1, mp2, mp3, mp5, mp8, mp9, mp10, mp12, mp13, mp15)
# hcr_list <- listN(mp1)

# 857, 1120, 1007, 895
set.seed(895)
nsims <- 9
seed_list <- sample(1:(1000*nsims), nsims)  # Draw 10 random seeds
# seed_list <- c(3,40,311,417,1105,1259,1581,1819,2078,2330,2512,2563,2719,2861,3190,3452,3709,3899,4233,4716,4723,4852,5160,5938,6264,6533,6754,7149,7207,7284,7329,7557,7579,8003,8388,8904)#ssb_data2 %>% pull(sim) %>% unique


mse_options_base <- setup_mse_options()
mse_options <- mse_options_base
mse_options$n_spinup_years <- 62
mse_options$recruitment_start_year <- 62
mse_options$n_proj_years <- 1
mse_options$run_estimation <- FALSE

om <- om_rand_recruit
om$model_options$obs_pars$ac_samps <- c(10, 5, 10, 5)
mp <- mp_f40

# mp5_modelrun <- run_mse_parallel(nsims, seed_list, om1, mp5, mse_options, nyears)

model_runs <- run_mse(
    om=om,
    mp=mp,
    mse_options=mse_options,
    seed=1120
)


spinup_years <- mse_options$n_spinup_years
nyears_input <- mse_options$n_proj_years + mse_options$n_spinup_years
do_survey_ll <- generate_annual_frequency(mp$ll_survey_frequency, nyears_input - spinup_years)
do_survey_tw <- generate_annual_frequency(mp$tw_survey_frequency, nyears_input - spinup_years)

y=64
survey_obs <- model_runs$survey_obs
aggregated_survey_obs <- aggregate_observations(survey_obs, 64)
aggregate_land_caa <- array(apply(model_runs$land_caa, c(1, 2, 3, 5), sum), dim=c(64, 30, 2, 1, 2))

assess_inputs <- simulate_em_data_sex_disaggregate(
    nyears = y,
    dem_params = afscOM::subset_dem_params(om$dem_params, 1:y, d=1, drop=FALSE),
    land_caa = aggregate_land_caa[1:y,,,,,drop=FALSE],
    survey_indices = afscOM::subset_dem_params(aggregated_survey_obs, 1:y, d=1, drop=FALSE),
    fxfish_caa_obs = afscOM::subset_matrix(aggregated_survey_obs$acs[1:y,,,,1,drop=FALSE], 1, d=5, drop=TRUE), # Age comp data is one year delayed
    twfish_caa_obs = afscOM::subset_matrix(aggregated_survey_obs$acs[1:y,,,,2,drop=FALSE], 1, d=5, drop=TRUE), # Age comp data is one year delayed
    ll_ac_obs = afscOM::subset_matrix(aggregated_survey_obs$acs[1:y,,,,3,drop=FALSE], 1, d=5, drop=TRUE), # Age comp data is one year delayed
    tw_ac_obs = afscOM::subset_matrix(aggregated_survey_obs$acs[1:y,,,,4,drop=FALSE], 1, d=5, drop=TRUE), # Age comp data is one year delayed
    ll_srv_indic = do_survey_ll[(spinup_years:y)-spinup_years+1],
    tw_srv_indic = do_survey_tw[(spinup_years:y)-spinup_years+1],
    model_options = om$model_options,
    added_years = y-spinup_years+1,
    file_suffix = y
)

mod_out <- fit_TMB_model(
    data = assess_inputs$new_data, 
    parameters = assess_inputs$new_parameters,
    model_name = "CurrentAssessmentDisaggregated"
)  
mod_report <- mod_out$report

mod_report

index_outs <- SpatialSablefishAssessment::get_index(mod_report)
index_outs <- index_outs %>% filter(observation %in% c("Domestic LL survey", "NMFS trawl survey"))

ggplot(index_outs)+
    geom_pointinterval(aes(x=Year, y=Observed, ymin=L_CI, ymax=U_CI))+
    geom_line(aes(x=Year, y=Predicted), color="red")+
    facet_wrap(~observation)+
    custom_theme


twl_rpw <- survey_obs$rpws[,,,,2,drop=FALSE]
apply(twl_rpw, 1, sum)

selex <- SpatialSablefishAssessment::get_selectivities(mod_report)
selex <- selex %>% filter(gear %in% c("domsurveyll", "fixed", "nmfssurveytrwl", "trawl"))

true_fish_selex <- reshape2::melt(om$dem_params$sel) %>% as_tibble() %>%
    filter(region == "BS") %>%
    rename("gear"="fleet") %>%
    select(-region) %>%
    mutate(
        gear = case_when(gear == "Fixed" ~ "fixed", TRUE ~ "trawl"),
        sex = case_when(sex == "F" ~ "female", TRUE ~ "male"),
        age = age-1,
        time_block = case_when(
            gear == "fixed" & time %in% 1:35 ~ 1,
            gear == "fixed" & time %in% 36:56 ~ 2,
            gear == "fixed" & time %in% 57:64 ~ 3,
            gear == "trawl" ~ 1
        )
    )

true_survey_selex <- reshape2::melt(om$dem_params$surv_sel) %>% as_tibble() %>%
    filter(region == "BS") %>%
    rename("gear"="fleet") %>%
    select(-region) %>%
    mutate(
        gear = case_when(gear == "Fixed" ~ "domsurveyll", TRUE ~ "nmfssurveytrwl"),
        sex = case_when(sex == "F" ~ "female", TRUE ~ "male"),
        age = age-1,
        time_block = case_when(
            gear == "domsurveyll" & time %in% c(1:56) ~ 1,
            gear == "domsurveyll" & time %in% c(57:64) ~ 2,
            gear == "nmfssurveytrwl" ~ 1
        )
    )

true_selex <- bind_rows(true_fish_selex, true_survey_selex)

full_selex <- selex %>% left_join(true_selex, by=c("age", "sex", "gear", "time_block"), suffix=c(".om", ".em"))


ggplot(full_selex)+
    geom_line(aes(x=age, y=value.om, linetype=factor(time_block)))+
    geom_line(aes(x=age, y=value.em, linetype=factor(time_block)), color="red")+
    facet_grid(rows = vars(sex), cols=vars(gear))+
    custom_theme

om_ssb <- apply(model_runs$naa[1:62,,1,,drop=FALSE]*om$dem_params$mat[1:62,,1,,drop=FALSE]*om$dem_params$waa[1:62,,1,,drop=FALSE], 1, sum)
est_ssb <- SpatialSablefishAssessment::get_SSB(mod_report)$SSB


plot(1:62, om_ssb, type="l", ylim=c(0, 300))
lines(1:64, est_ssb, col="red")

est_ssb <- apply(model_runs$naa_est[1:62,,1,,drop=FALSE]*om$dem_params$mat[1:62,,1,1,drop=FALSE]*om$dem_params$waa[1:62,,1,1,drop=FALSE], 1, sum)


om_rec <- apply(model_runs$naa[1:62,1,,,drop=FALSE], 1, sum)
est_rec <- apply(model_runs$naa_est[1:62,1,,,drop=FALSE], 1, sum)

mod_out$opt

exp(3.0296574668)

SpatialSablefishAssessment::get_recruitment(mod_report)$Recruitment
