#' Aggregate Survey Index Observations
#' 
#' Given observations of survey indices generated by the OM (afscOM::simulate_observations)
#' across more than one region, aggregate such indices to a single region by summing
#' across regions.
#' 
#' @param survey_obs list of survey observations that include an RPN and RPW elements of
#' dimension [nyears, 1, 1, nregions, nsurveys]
#' @param y the terminal year of survey observations to perform aggregation on
#' 
#' @return list of RPN and RPW indices aggregated to a single spatial dimension
#' 
#' @export aggregate_indices
#'  
aggregate_indices <- function(survey_obs, y){

    out_dims1 <- dim(survey_obs$rpns)
    out_dims1[1] <- y
    out_dims1[4] <- 1

    aggregate_obs <- list(
        rpns = array(apply(survey_obs$rpns, c(1, 5), \(x) sum(x))[1:y,], dim=out_dims1),
        rpws = array(apply(survey_obs$rpws, c(1, 5), \(x) sum(x))[1:y,], dim=out_dims1)
    )

    return(aggregate_obs)

}

#' Generate Regionally Weighted Aggregated Age Compositions 
#' 
#' Create a single-region aggregate age composition from a spatially-explicit
#' OM. Regional age-compositions are weighted by modifying the ISS to the
#' random multinomial draw based on the proportion of stock biomass or total
#' landings in each region. This deviates slightly from the operational method,
#' where regional weights come from the LL RPW index and CAA in numbers of
#' inidviduals.
#' 
#' @param dem_params list of demographic parameters from the OM [1, nages, nsexes, nregions, nfleets]
#' @param naa array of numbers at age [1, nages, nsexes, nregions]
#' @param caa array of catch at age [1, nages, nsexes, nregions
#' @param obs_pars list of observation parameters from OM
#' 
#' @return array of age compositions [1, nages, nsexes, 1, nfleets+surveys]
#' 
#' @export generate_aggregate_comps
#' 
generate_aggregate_comps <- function(dem_params, naa, caa, obs_pars){
    nfleets <- dim(dem_params$sel)[5]
    nsurveys <- dim(dem_params$surv_sel)[5]

    tmp <- array(NA, dim=c(1, 30, 2, 1, nfleets+nsurveys))

    for(i in 1:(nfleets+nsurveys)){
        ISS <- obs_pars$ac_samps[i]
        agg_sex <- obs_pars$acs_agg_sex[i]
        as_int <- obs_pars$ac_as_integers[i]

        is_survey <- obs_pars$is_survey[i]
        if(is_survey){
            selex <- subset_matrix(dem_params$surv_sel, r=i-2, d=5, drop=TRUE)
            weights <- apply(naa*dem_params$waa, c(1, 4), sum)
        }else{
            selex <- subset_matrix(dem_params$sel, r=i, d=5, drop=TRUE)
            weights <- apply(caa, c(1, 4), sum) # this is landings (caa*weight)
        }

        agg_comp <- simulate_weighted_comps_ISS(
            aa_matrix = naa,
            region_weights = weights,
            selex = selex,
            total_samples = ISS,
            aggregate_sex = agg_sex,
            as_integers = as_int
        )

        tmp[,,,,i] <- agg_comp
    }

    return(tmp)
}


simulate_weighted_comps_ISS <- function(aa_matrix, selex, region_weights, total_samples, aggregate_sex, as_integers, return_agg=TRUE){

    std_region_weights <- as.vector(region_weights/sum(region_weights))
    
    regional_samples <- round(total_samples*std_region_weights, 0)

    nregions <- afscOM::get_model_dimensions(selex)$nregions
    ac_obs_out <- array(NA, dim=c(1, 30, 2, nregions, 1))
    for(r in 1:nregions){
        ac <- afscOM::simulate_ac(aa_matrix[,,,r,drop=FALSE], selex[,,,r,drop=FALSE], aggregate_sex=aggregate_sex)
        tmp <- afscOM::simulate_multinomial_obs(
            ac,
            regional_samples[r], 
            aggregate_sex = aggregate_sex,
            as_integers=as_integers
        )

        ac_obs_out[1,,,r,1] <- tmp
    }
    
    if(return_agg){
        return(array(apply(ac_obs_out, c(1, 2, 3, 5), sum), dim=c(1,30,2,1,1)))
    }else{
        return(ac_obs_out)
    }

}

# simulate_weighted_comps_SAMPLE <- function(aa_matrix, selex, region_weights, total_samples, aggregate_sex, as_integers){

#     std_region_weights <- as.vector(region_weights/sum(region_weights))
    
#     # aa_total <- array(apply(aa_matrix, c(1, 2, 3), sum), dim=c(1, 30, 2, 1))

#     ##### This is wrong, FIX later
#     ac <- afscOM::simulate_ac(aa_matrix, selex, aggregate_sex=aggregate_sex)
    
#     aa_total <- array(apply(ac*std_region_weights, c(1, 2, 3), sum), dim=c(1, 30, 2, 1))

#     tmp <- afscOM::simulate_multinomial_obs(
#         aa_total, 
#         total_samples, 
#         aggregate_sex = aggregate_sex,
#         as_integers=as_integers
#     )

#     ac_obs_out <- array(NA, dim=c(1, 30, 2, 1, 1))
#     ac_obs_out[1,,,1,1] <- tmp
#     return(ac_obs_out)

# }

# simulate_weighted_comps_HYRBID <- function(aa_matrix, selex, region_weights, total_samples, aggregate_sex, as_integers){
#     std_region_weights <- as.vector(region_weights/sum(region_weights))
#     ISS_weighted_comps <- simulate_weighted_comps_ISS(aa_matrix, selex, region_weights, total_samples, aggregate_sex, as_integers, return_agg=FALSE)
#     regional_samples <- round(total_samples*std_region_weights, 0)

#     weighted_comp <- sweep(ISS_weighted_comps, 4, std_region_weights, FUN="*")
#     std_weighted_comp <- array(NA, dim=dim(weighted_comp))
#     for(r in 1:length(regional_samples)){
#         tmp <- weighted_comp[,,,r,,drop=FALSE]/sum(weighted_comp[,,,r,,drop=FALSE])
#         std_weighted_comp[,,,r,] <- tmp
#     }

#     full_weighted_comp <- sweep(std_weighted_comp, 4, regional_samples, FUN="*")
    
#     total_comp <- array(apply(full_weighted_comp, c(1, 2, 3), sum), dim=c(1, 30, 2, 1))
#     return(total_comp)
# }

# simulate_weighted_comps <- function(ac, weight_type, selex, weights, total_samples, aggregate_sex, as_integers){
#     if(weight_type == 1){
#         agg_comp <- simulate_weighted_comps_ISS(ac, selex, weights, total_samples, aggregate_sex, as_integers)
#     }else if(weight_type == 2){
#         agg_comp <- simulate_weighted_comps_SAMPLE(ac, selex, weights, total_samples, aggregate_sex, as_integers)
#     }else{
#         agg_comp <- simulate_weighted_comps_HYRBID(ac, selex, weights, total_samples, aggregate_sex, as_integers)
#     }
#     return(agg_comp)
# }
